# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["ehci_pci" "ahci" "megaraid_sas" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  # nvme zfs drive

  # nvme drive
  fileSystems."/var/lib/libvirt/images" = {
    device = "vmpool/images";
    fsType = "zfs";
  };
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1cc058e9-6f83-4ca5-a7b7-7b9fed099922";
    fsType = "ext4";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/14de00c7-3c9c-4c0d-9360-c86e84902007";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
