keys:
  - &deathraymind age1psgzl6fsfu8397ezxuryzyutuw8vdzsehkemjxwqdajl4cf3fpksl3974a 
  - &pelican_host age1cwvdyxvgx6jjv95ztp5y9n0v4th2k4uur68ts2rdr9e3qjpul4gs4kuss8 
creation_rules:
  - path_regex: secrets/pelican\.yaml$
    key_groups:
      - age:
          - *deathraymind
          - *pelican_host
